# Use root/exampleRoot as user/password credentials
version: '3.4'

volumes:
  mysql_volume:
    name: ${DOCKER_MYSQL_DB_VOLUME}
    external: false


services:

  db:
    image: mariadb
    restart: always
    container_name: app_mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
      
      # - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3310:3306
    volumes:
      - mysql_volume:/var/lib/mysql
      # for init scripts, will be consumed/imported during start
      - ./mysql/scripts/:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    restart: always
    container_name: app_adminer
    ports:
      - 8088:8080
