apiVersion: 1

datasources:
- name: InfluxDB
  type: influxdb
  access: proxy
  url: http://localhost:8086
  database: testdatabase
  user: testuser
  password: testpassword
  basicAuth: true
  isDefault: true
  editable: false
