# https://prometheus.io/docs/prometheus/latest/getting_started/
global:
    scrape_interval: 5s
    external_labels:
        monitor: 'test-monitor'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090'] 

#  - job_name: 'node'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['your_server_ip:9100']        
