version: '3.6'

services:

  influxdb:
    container_name: influxdb
    image: influxdb:1.8-alpine
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_DB=influx # telegraf_metrics
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    container_name: grafana-server # grafana
    image: grafana/grafana
    ports:
      - '3000:3000'
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    volumes:
    
      - grafana_data:/var/lib/grafana

  telegraf:
    container_name: telegraf
    image: telegraf:latest
    ports:
      - '8125:8125'
    volumes:
      # configuration file for telegraf
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - grafana
    links:
      - influxdb

volumes:
  grafana_data: {}
  influxdb_data: {}