version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.5
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - elk
  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.5
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.16.5
    container_name: logstash
    ports:
      - 5044:5044 # Example: Beats input
      - 9300:9300 # Logstash monitoring API
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline # Mount your Logstash pipeline configuration
      - ./logstash/config:/usr/share/logstash/config # Mount your Logstash configuration
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m # Adjust memory as needed
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk

networks:
  elk:
    driver: bridge
